name: Build and Test Workflow

on:
  pull_request

jobs:
  build:
    name: Built and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node_version: ${{ matrix.node_version }}
      - run: |
          npm ci
          npm run build
          npm run test
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
